--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/platz1de/Waterlogging
build-by-default: true
branches:
- master
projects:
  Waterlogging:
    path: ""
    lint:
      phpstan: false
...
